import './globals.css'

export const metadata = {
  title: 'AI Niche App',
  description: 'Generated by Master Bootstrap',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-XXXXXXXXXXXXXXXX" crossOrigin="anonymous"></script>
      </head>
      <body style={{ margin: 0, backgroundColor: '#0a0a0a' }}>
        {children}
      </body>
    </html>
  )
}